services:
  nginx:
    container_name: nginx
    restart: unless-stopped
    depends_on:
      - php
    build:
      context: docker/nginx
      args:
        SERVER_VERSION: $SERVER_VERSION
    tty: true
    stdin_open: true
    env_file: ./.env
    working_dir: $PHP_USER_HOME_DIRECTORY
    volumes:
      # - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./:$PHP_USER_HOME_DIRECTORY
      - ./docker/nginx/templates:/etc/nginx/templates
      - /etc/letsencrypt:/etc/letsencrypt:ro
    ports:
      - $SERVER_PORT:80

  php:
    container_name: php
    restart: unless-stopped
    depends_on:
      - mysql
    build:
      context: docker/php
      args:
        PHP_VERSION: $PHP_VERSION
        PHP_USER_NAME: $PHP_USER_NAME
        PHP_USER_IDENTIFIER: $PHP_USER_IDENTIFIER
        PHP_USER_SHELL: $PHP_USER_SHELL
        PHP_USER_HOME_DIRECTORY: $PHP_USER_HOME_DIRECTORY
    tty: true
    stdin_open: true
    env_file: .env
    working_dir: $PHP_USER_HOME_DIRECTORY
    user: php
    volumes:
      - ./:$PHP_USER_HOME_DIRECTORY

  migration:
    container_name: migration
    restart: unless-stopped
    depends_on:
      - mysql
    build:
      context: docker/php
      args:
        PHP_VERSION: $PHP_VERSION
        PHP_USER_NAME: $PHP_USER_NAME
        PHP_USER_IDENTIFIER: $PHP_USER_IDENTIFIER
        PHP_USER_SHELL: $PHP_USER_SHELL
        PHP_USER_HOME_DIRECTORY: $PHP_USER_HOME_DIRECTORY
    tty: true
    stdin_open: true
    env_file: .env
    working_dir: $PHP_USER_HOME_DIRECTORY
    user: php
    volumes:
      - ./db:$PHP_USER_HOME_DIRECTORY

  mysql:
    container_name: mysql
    restart: unless-stopped
    build:
      context: docker/mysql
      args:
        DATABASE_VERSION: $DATABASE_VERSION
    tty: true
    stdin_open: true
    user: root
    env_file: .env
    working_dir: /var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: $DATABASE_ROOT_PASSWORD
      MYSQL_USER: $DATABASE_USER
      MYSQL_PASSWORD: $DATABASE_PASSWORD
      MYSQL_DATABASE: $DATABASE_NAME
    volumes:
      - ./database:/var/lib/mysql

  phpmyadmin:
    container_name: phpmyadmin
    restart: unless-stopped
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: mysql
      PMA_USER: $DATABASE_USER
      PMA_PASSWORD: $DATABASE_ROOT_PASSWORD
      PMA_PORT: 3306
    ports:
      - "8080:80"
    depends_on:
      - mysql
